language: python
python:
 - "2.7"
addons:
  apt:
    packages:
      - openjdk-8-jre  # install Java8 as required by vnu.jar

install:
  - pip install html5validator

script:
  - html5validator

after_success:
  - test "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" || exit 0
  - git clone --depth 1 https://${GH_TOKEN}@github.com/openturns/openturns.github.io.git
  - mkdir -p openturns.github.io/openturns/www
  - cp -r index.html _images _static bootstrap2 favicon.ico openturns.github.io/openturns/www
  - cd openturns.github.io
  - touch .nojekyll
  - git config user.email "support@travis-ci.com"
  - git config user.name "Travis CI"
  - git add -A .
  - git commit -a -m "Travis build www ${TRAVIS_BUILD_NUMBER}"
  - git push --quiet origin master > /dev/null 2>&1

env:
  global:
    secure: Ib6jdATV0rEiPoNSQTH56AOYePEVQ5IXvYmm50EJ+5Ap6X3tqx2LOljDU148qZkHoGyPCQClwxsJHDEfDYD3zpCAmVscKeXwrlPE6gG9uDByAQ5hvk6jAZXehC8g3H7F+SM0ikakjdUV1bhWW7TkeNRr6yy3cuIQLcZsTzcKjf3RF1+AAK4DOBG/z+/zSmYRUfkb5ZpvCIe2xsZE/IyEHyheUo1wR4tM7+nyQrmwRcFDqv3gSIsOhByGw159NFqHV+gNO3Y0yekl4V6GirR9HkHaFH4zO5LIAkGvm+OdB1tlwkJAKE9wwl5GVADaDQWrJJLoUAVCf4V9rtt0o+lpw0sFcpQelscJ4mKTgGnddEXTzX0n1mDActvhMkpGhg3eF6Q0rDIdAEKR3rPRgkBrtjyrS2yVT7btDSqiBnaag5lxVSOFeRkrk9iP5uF0kdfkNCzV5S3PkE3E4e2sk7ib1D5M0mYpEfG6OVwUr1dQvBqMQyZfHBkbHhzJjZFJJS+lgZ2/SYA0qhAwuHUBtoO2OR1acRQJbvNK7U1b5gKSc53mXcEmzAbzdmlTwuTP7ZGaG+zgc3N04XTGpIcI0DZDGXtbeqK1nQkzf2wn6Up8OvQ7wXsP+G3+swezrXH7EwRkj/XE04SgHL/eB2tiW64AIvAp52vKp9OdtbYLRjKCKIs=
